  name: ReactJs CI

  on:
    push:
      branches: [ develop ]
    pull_request:
      branches: [ develop ]

  jobs:
    build:

      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [14.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - run: npm i
        - run: CI='' npm run build --if-present

        - name: Upload folder build
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            # file want to copy
            source: "build"
            # the destination of file
            target: "/home/ubuntu/FE"
        - name: Start service
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            script: |
              sudo systemctl stop deploy-fe
              sudo sudo systemctl daemon-reload
              sudo systemctl start deploy-fe
